'use server';
/**
 * @fileOverview This file implements a Genkit flow for recommending the most optimal VPN server
 * based on user needs and generating the WireGuard configuration for it.
 *
 * - recommendServerConfig - A function that handles the server recommendation process.
 * - RecommendServerConfigInput - The input type for the recommendServerConfig function.
 * - RecommendServerConfigOutput - The return type for the recommendServerConfig function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import {getFirestore} from 'firebase-admin/firestore';
import {initializeApp, getApps, getApp} from 'firebase-admin/app';
import fetch from 'node-fetch';

// Ensure firebase-admin app is initialized. This is a common pattern for server-side Firebase operations.
if (getApps().length === 0) {
  initializeApp();
}
const firestore = getFirestore();

// Define input schema for the flow and prompt
const RecommendServerConfigInputSchema = z.object({
  vpnNeeds: z.string().describe('A description of the user\'s VPN needs (e.g., "fastest connection for streaming", "maximum privacy", "access content from Japan").'),
  clientPublicKey: z.string().describe('The WireGuard client public key generated on the client-side.'),
  idToken: z.string().describe('The Firebase Authentication ID Token of the authenticated user. This is crucial for authenticating calls to Firebase Functions.'),
  uid: z.string().optional().describe('The Firebase User ID of the authenticated user. Derived from idToken but can be explicitly passed.'),
});
export type RecommendServerConfigInput = z.infer<typeof RecommendServerConfigInputSchema>;

// Define output schema for the prompt part
const PromptOutputSchema = z.object({
  recommendedServerId: z.string().describe('The ID of the recommended VPN server.'),
  explanation: z.string().describe('A brief explanation of why this server was recommended.'),
});
type PromptOutput = z.infer<typeof PromptOutputSchema>;

// Define output schema for the entire flow, combining prompt output with WireGuard config details
const RecommendServerConfigOutputSchema = z.object({
  recommendedServerId: z.string().describe('The ID of the recommended VPN server.'),
  explanation: z.string().describe('A brief explanation of why this server was recommended.'),
  wireguardConfigDetails: z.object({
    serverEndpoint: z.string().describe('The endpoint of the recommended VPN server.'),
    serverPublicKey: z.string().describe('The public key of the recommended VPN server.'),
    clientAddress: z.string().describe('The client IP address allocated for the user.'),
    dns: z.array(z.string()).describe('DNS servers to be used by the client.'),
  }).describe('The server-side WireGuard configuration details generated by Firebase Function.'),
});
export type RecommendServerConfigOutput = z.infer<typeof RecommendServerConfigOutputSchema>;

// Helper function to call the Firebase Callable Function 'generateWgConfig'
// This function simulates a client-side call to the HTTPS Callable function from a server context,
// by including the ID token in the Authorization header.
async function callGenerateWgConfigFirebaseFunction(
  idToken: string,
  serverId: string,
  clientPublicKey: string,
  projectId: string = process.env.FIREBASE_PROJECT_ID || 'your-firebase-project-id' // Default project ID, replace 'your-firebase-project-id'
): Promise<RecommendServerConfigOutput['wireguardConfigDetails']> {
  if (!projectId || projectId === 'your-firebase-project-id') {
    console.warn('FIREBASE_PROJECT_ID environment variable is not set. Defaulting to a placeholder.');
    // In a production environment, you might want to throw an error here.
  }
  const functionsUrl = `https://us-central1-${projectId}.cloudfunctions.net/generateWgConfig`;

  const response = await fetch(functionsUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${idToken}`,
    },
    body: JSON.stringify({
      data: {
        serverId,
        clientPublicKey,
      },
    }),
  });

  if (!response.ok) {
    let errorMessage = `Failed to call generateWgConfig Firebase Function: ${response.status} ${response.statusText}`;
    try {
      const errorBody = await response.json();
      errorMessage += ` - ${errorBody.error?.message || JSON.stringify(errorBody)}`;
    } catch (e) {
      // response body might not be JSON
    }
    throw new Error(errorMessage);
  }

  const {result} = await response.json() as { result: RecommendServerConfigOutput['wireguardConfigDetails'] };
  return result;
}


// Genkit prompt definition. This prompt will leverage an LLM to recommend a server.
const recommendServerPrompt = ai.definePrompt({
  name: 'recommendServerPrompt',
  input: {schema: RecommendServerConfigInputSchema.pick({vpnNeeds: true}).extend({serversJson: z.string()})},
  output: {schema: PromptOutputSchema},
  prompt: `You are an intelligent VPN server recommender.
Your task is to analyze the user's VPN needs and select the most optimal server from the provided list.
Also, provide a concise explanation for your recommendation.

User's VPN Needs: "{{{vpnNeeds}}}"

Available Servers (JSON array):
{{{serversJson}}}

Each server object has the following properties:
- id: string (Unique identifier)
- name: string (Human-readable name)
- endpoint: string (VPN server endpoint)
- publicKey: string (WireGuard server public key)
- country: string (ISO 3166-1 alpha-2 country code)
- city: string
- load: number (0-100%, lower is better)
- latency: number (ms, lower is better)
- supportsUdp: boolean (Whether direct WireGuard UDP is supported)
- supportsTcpTunnel: boolean (Whether UDP-over-TCP for Tor is supported)
- isActive: boolean (Must be true)

Consider the following criteria for recommendation:
- For "fastest connection", prioritize servers with low latency and low load.
- For "maximum privacy" or "Tor", prioritize servers that support TCP tunneling (supportsTcpTunnel: true) or generally have high privacy assurances.
- For "access content from [country]", prioritize servers in that specific country.
- Always ensure the recommended server has 'isActive: true'.

Your output MUST be a JSON object conforming to the following schema:
${JSON.stringify(PromptOutputSchema.shape, null, 2)}
`,
});

// Genkit flow definition. This flow orchestrates fetching data, calling the LLM, and generating config.
const recommendServerConfigFlow = ai.defineFlow(
  {
    name: 'recommendServerConfigFlow',
    inputSchema: RecommendServerConfigInputSchema,
    outputSchema: RecommendServerConfigOutputSchema,
  },
  async (input) => {
    // 1. Fetch active servers from Firestore
    const serversSnapshot = await firestore
      .collection('servers')
      .where('isActive', '==', true)
      .get();

    const availableServers = serversSnapshot.docs.map((doc) => ({
      id: doc.id,
      ...doc.data(),
    }));

    if (availableServers.length === 0) {
      throw new Error('No active VPN servers available to recommend.');
    }

    // 2. Prepare input for the recommendation prompt
    const promptInput = {
      vpnNeeds: input.vpnNeeds,
      serversJson: JSON.stringify(availableServers),
    };

    // 3. Call the Genkit prompt to get the recommended server ID and explanation
    const { output } = await recommendServerPrompt(promptInput);

    if (!output?.recommendedServerId) {
      throw new Error('AI failed to recommend a server ID from the available options.');
    }

    const recommendedServer = availableServers.find(
      (s) => s.id === output.recommendedServerId
    );

    if (!recommendedServer) {
      // This check ensures the AI recommended a valid, active server from the list provided.
      throw new Error(`Recommended server with ID '${output.recommendedServerId}' not found or is no longer active.`);
    }

    // 4. Call the Firebase Cloud Function to generate WireGuard config details for the recommended server
    // This relies on the Firebase project ID being correctly set in the environment.
    const wireguardConfigDetails = await callGenerateWgConfigFirebaseFunction(
      input.idToken,
      recommendedServer.id,
      input.clientPublicKey,
      process.env.FIREBASE_PROJECT_ID
    );

    // 5. Return the combined result, including the AI's recommendation and the generated config details
    return {
      recommendedServerId: output.recommendedServerId,
      explanation: output.explanation,
      wireguardConfigDetails: wireguardConfigDetails,
    };
  }
);

// Exported wrapper function to be called from the client-side.
export async function recommendServerConfig(
  input: RecommendServerConfigInput
): Promise<RecommendServerConfigOutput> {
  return recommendServerConfigFlow(input);
}
